[package]
name = "psp"
version = "0.1.0"
authors = ["icew4ll <icew4ll.io>"]

[dependencies]
chrono = "0.4.3"
clap = "2.31.2"
duct = "0.10.0"
dotenv_codegen = "0.11.0"
lazy_static = "1.0.1"
regex = "1.0.0"
maxminddb = "0.9.0"
serde_json = "1.0.21"
prettytable-rs = "0.7.0"
